services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: orcamento_mz
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sua_senha_segura_123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/orcamento_mz
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: hercio.123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db
    networks:
      - orcamento-net

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - orcamento-net

networks:
  orcamento-net:
    driver: bridge

volumes:
  postgres_data: