services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: orcamento_mz
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hercio.123          # ← muda esta senha se quiseres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .                    # raiz do projeto
      dockerfile: Dockerfile.backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/orcamento_mz
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: hercio.123   # ← tem de ser IGUAL à de cima
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      - db

volumes:
  postgres_data: