spring.datasource.url=jdbc:postgresql://localhost:5432/orcamento_mz
spring.datasource.username=wesley
spring.datasource.password=hecio.123
spring.jpa.hibernate.ddl-auto=update  
spring.jpa.show-sql=true